*.sink.prometheusServlet.class=org.apache.spark.metrics.sink.PrometheusServlet
*.sink.prometheusServlet.path=/metrics/prometheus
master.sink.prometheusApplications.class=org.apache.spark.metrics.sink.PrometheusServlet
master.sink.prometheusApplications.path=/metrics/applications/prometheus
master.source.jvm.class=org.apache.spark.metrics.source.JvmSource
worker.source.jvm.class=org.apache.spark.metrics.source.JvmSource
master.source.jvmCPU.class=org.apache.spark.metrics.source.JVMCPUSource
worker.source.jvmCPU.class=org.apache.spark.metrics.source.JVMCPUSource
driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource
executor.source.jvm.class=org.apache.spark.metrics.source.JvmSource
driver.source.jvmCPU.class=org.apache.spark.metrics.source.JVMCPUSource
executor.source.jvmCPU.class=org.apache.spark.metrics.source.JVMCPUSource
executor.sink.statsd.class=org.apache.spark.metrics.sink.StatsdSink
executor.sink.statsd.host=statsd-exporter
executor.sink.statsd.port=9125
executor.sink.statsd.period=10
executor.sink.statsd.unit=seconds
executor.sink.statsd.prefix=spark
